/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.32
 * Generated at: 2022-05-27 04:04:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import bean.Book;
import util.MyFormat;

public final class update_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/view/../../common/header.jsp", Long.valueOf(1652936344346L));
    _jspx_dependants.put("/view/../../common/footer.jsp", Long.valueOf(1652082244462L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("bean.Book");
    _jspx_imports_classes.add("util.MyFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>書籍変更</title>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h1 align=\"center\">書籍管理システムweb版ver.2.0</h1>\r\n");
      out.write("<hr align=\"center\" size=\"5\" color=\"blue\" width=\"950\">");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<table align=\"center\" width=\"900\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"80\">[<a href=\"");
      out.print(request.getContextPath() );
      out.write("/view/menu.jsp\">メニュー</a>]</td>\r\n");
      out.write("\t\t\t\t<td width=\"80\">[<a href=\"");
      out.print(request.getContextPath() );
      out.write("/list\">書籍一覧</a>]</td>\r\n");
      out.write("\t\t\t\t<td width=\"80\">[<a href=\"");
      out.print(request.getContextPath() );
      out.write("/view/insert.jsp\">書籍登録</a>]</td>\r\n");
      out.write("\t\t\t\t<td width=\"380\" align=\"center\" ><font size=\"5\">書籍変更</font></td>\r\n");
      out.write("\t\t\t\t<td width=\"140\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td width=\"140\">&nbsp;</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");

MyFormat format = new MyFormat();
Book book = (Book)request.getAttribute("book");
//リクエストスコープからのデータの取得
String isbn = book.getIsbn();
String title = book.getTitle();
int price = book.getPrice();

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<hr align=\"center\" size=\"2\" color=\"black\" width=\"950\"></hr>\r\n");
      out.write("\r\n");
      out.write("\t\t<br><br><br>\r\n");
      out.write("<form action=\"");
      out.print(request.getContextPath());
      out.write("/update\" method=\"get\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"isbn\" value=");
      out.print(isbn);
      out.write("></input>\r\n");
      out.write("\t\t<table summary=\"詳細表示\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th><div><<変更前情報>></div></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th  width=\"50\"></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th><div><<変更後情報>></div>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th style=\"background-color:#6666ff; texr-align:left\" width=\"150\" >ISBN</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th style=\"background-color:#00FFFF; texr-align:left\" width=\"150\" >");
      out.print( isbn );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th style= texr-align:left\" width=\"150\" >");
      out.print( isbn );
      out.write("</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th style=\"background-color:#6666ff; texr-align:left\" width=\"150\" >タイトル</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th style=\"background-color:#00FFFF; texr-align:left\" width=\"150\" >");
      out.print( title );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th><input type=\"text\" name=\"title\" ></input></th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th style=\"background-color:#6666ff; texr-align:left\" width=\"150\" >価格</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th style=\"background-color:#00FFFF; texr-align:left\" width=\"150\" >");
      out.print( format.moneyFormat(price) );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th><input type=\"text\" name=\"price\" ></input></th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t\t<input type=submit value=\"変更完了\" style=\"background:#ffffff; color:#000000;\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<br><br><br><br><br><br><br><br><br>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr align=\"center\" size=\"5\" color=\"blue\" width=\"950\">\r\n");
      out.write("\t\t<table border=0 align=\"center\" width=\"950\" summary=\"フッター表示\">\r\n");
      out.write("\t\t\t<tr><td>copyright (c) 2022 all rights reserved.</td></tr>\r\n");
      out.write("\t\t</table>");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
